# k8s/external-secret.yml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager-store
  namespace: external-secrets # Or the namespace where External Secrets operator is running
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1 # <--- REPLACE WITH YOUR AWS_REGION
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa # Service Account for External Secrets operator
            namespace: external-secrets # Namespace of the SA

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gcp-pubsub-credentials-ext
  namespace: hello-keda-app # Namespace where the K8s Secret will be created
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager-store
    kind: SecretStore
  target:
    name: gcp-pubsub-credentials-k8s # Name of the Kubernetes Secret that will be created
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        "key.json": "{{ .gcp_sa_key }}" # 'gcp_sa_key' must match the key used in AWS Secrets Manager
  dataFrom:
    - secretKey: gcp-pubsub-credentials # Name of your secret in AWS Secrets Manager