# k8s/iam-role-service-account.yml
# Service Account for your Python application pods
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keda-app-sa # Service Account for all Python app deployments
  namespace: hello-keda-app
  annotations:
    # This annotation links the K8s Service Account to an AWS IAM Role.
    # Replace <YOUR_AWS_ACCOUNT_ID> and <YOUR_IAM_ROLE_NAME_FOR_KEDA_APP_SA>
    eks.amazonaws.com/role-arn: arn:aws:iam::<YOUR_AWS_ACCOUNT_ID>:role/<YOUR_IAM_ROLE_NAME_FOR_KEDA_APP_SA>

---
# Service Account for the External Secrets Operator
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa # Service Account for External Secrets operator
  namespace: external-secrets
  annotations:
    # This annotation links the K8s Service Account to an AWS IAM Role.
    # Replace <YOUR_AWS_ACCOUNT_ID> and <YOUR_IAM_ROLE_NAME_FOR_EXTERNAL_SECRETS_SA>
    eks.amazonaws.com/role-arn: arn:aws:iam::<YOUR_AWS_ACCOUNT_ID>:role/<YOUR_IAM_ROLE_NAME_FOR_EXTERNAL_SECRETS_SA>