# k8s/namespace.yml
apiVersion: v1
kind: Namespace
metadata:
  name: hello-keda-app
---
apiVersion: v1
kind: Namespace
metadata:
  name: keda
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets